export enum GameEvents {
  ITEM_MOVEMENT_END = 'item_movement_end',
  MATCH_FOUND = 'match_found',
  MATCH_HANDLED = 'match_handled',
  CASCADE_COMPLETE = 'cascade_complete',
  BOARD_SETTLED = 'board_settled',
  SWAP_REQUESTED = 'swap_requested',
  SWAP_COMPLETED = 'swap_completed',
  SWAP_FAILED = 'swap_failed',
  BOOSTER_CREATED = 'booster_created',
  BOOSTER_ACTIVATED = 'booster_activated',
  BOOSTER_MERGE = 'booster_merge',
  MOVE_USED = 'move_used',
  GOAL_PROGRESS = 'goal_progress',
  LEVEL_COMPLETE = 'level_complete',
  LEVEL_FAILED = 'level_failed',
  UI_BOOSTER_SELECTED = 'ui_booster_selected',
  SCORE_CHANGED = 'score_changed',
}
